name: CI

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  terraform:
    name: Terraform Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Format Check
        run: terraform fmt -check -recursive terraform

      - name: Terraform Init
        working-directory: terraform/environments/staging
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: terraform/environments/staging
        run: terraform validate

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4

      - name: TFLint Init
        working-directory: terraform/environments/staging
        run: tflint --init

      - name: TFLint
        working-directory: terraform/environments/staging
        run: tflint

  docker:
    name: Docker Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        working-directory: app
        run: |
          docker build -t infra-as-code-pipeline:test .
